const $=s=>document.querySelector(s), state={data:null};
const titles={command:'Command Center',brain:'Progressive Brain',research:'Research',company:'Company',sector:'Sector Intelligence',portfolio:'Portfolio Intelligence',risk:'Risk Engine',scenarios:'Scenario Laboratory',allocation:'Allocation Brain',learning:'Learning Loop',replay:'Time Machine',operations:'Operations',data:'Data Plane',performance:'Performance',security:'Security'};
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#title').textContent=titles[v];$('#sectionLabel').textContent=titles[v].toUpperCase();window.scrollTo({top:0,behavior:'smooth'});if(v==='brain')loadHistory();if(v==='replay')loadCycles();if(v==='operations')loadAudit();if(v==='data')loadProviders();if(v==='performance')loadPerformance();if(v==='learning')loadLearning();if(v==='risk')loadRisk()}
document.querySelectorAll('[data-view]').forEach(x=>x.addEventListener('click',()=>showView(x.dataset.view)));
const n=(v)=>v===null||v===undefined||v===''?'—':(typeof v==='number'?v.toLocaleString(undefined,{maximumFractionDigits:3}):v);
function metric(label,value,detail=''){return `<div class="metric"><small>${label}</small><b>${n(value)}</b><em>${detail}</em></div>`}
function render(d){state.data=d;const h=d.health||{},p=d.paper||{},b=d.brain||{},o=d.operations||{};$('#connection').textContent=h.status||'UNKNOWN';$('#heroStatus').textContent=h.status||'UNKNOWN';$('#heroDetail').textContent=h.status==='OK'?'Audit + safety checks verified':'Runtime requires attention';
$('#headlineMetrics').innerHTML=metric('Runtime',h.status,'control plane')+metric('Brain memory',b.memory_states,'persisted states')+metric('Paper P&L',p.unrealized_pnl,'unrealized')+metric('Audit events',d.journal?.events,'journal records');
$('#brainSummary').innerHTML=b.latest_cycle?`<b>Cycle ${b.latest_cycle}</b><div class="muted">Phase ${b.phase||'—'} · uncertainty ${n(b.uncertainty)} · fragility ${n(b.fragility)} · robustness ${n(b.robustness)}</div>`:'No reasoning cycle has been executed yet.';
$('#portfolioSummary').innerHTML=p.position_count?`<b>${p.position_count} paper positions</b><div class="muted">Gross market value ${n(p.gross_market_value)} · unrealized P&L ${n(p.unrealized_pnl)}</div>`:'No paper positions yet.';
$('#researchReadiness').innerHTML=`<div><b>Dataset contract</b><span>${(d.research?.required_datasets||[]).length} required datasets</span></div><div><b>Provider</b><span>${d.research?.coverage_contract?.provider_ready?'READY':'NOT CONFIGURED'}</span></div><div><b>Forecasts</b><span>${d.learning?.forecasts??0}</span></div><div><b>Replay snapshots</b><span>${d.replay?.snapshots??0}</span></div>`;$('#dataBoundary').innerHTML=`<div><span>Integrity pipeline</span><b>${d.integrity?.status||'—'}</b></div>`+`<div><span>Market data</span><b>${d.data_boundary?.market_data||'—'}</b></div><div><span>PIT</span><b>${d.data_boundary?.pit?'ENFORCED':'—'}</b></div><div><span>Synthetic market feed</span><b>${d.data_boundary?.synthetic_market_data?'ALLOWED':'DISABLED'}</b></div>`;
$('#brainMetrics').innerHTML=metric('Memory states',b.memory_states,'persistent')+metric('Phase',b.phase,'current')+metric('Uncertainty',b.uncertainty,'explicit')+metric('Fragility',b.fragility,'explicit');
const phases=['OBSERVE','HYPOTHESIZE','EVIDENCE CHECK','CHALLENGE','FALSIFY','COUNTERFACTUAL','SCENARIO','UNCERTAINTY','RISK','DECIDE','MONITOR','REOPEN','OUTCOME','ATTRIBUTION','CALIBRATION','MODEL COMPARISON','LEARN','UPDATE BELIEF','NEXT CYCLE'];$('#phaseMap').innerHTML=phases.map(x=>`<div class="${x===b.phase?'current':''}">${x}</div>`).join('');
$('#researchJobs').textContent=o.research_jobs??'—';
$('#universeTarget').textContent=d.research?.universe_target_size??'—';$('#activeJobs').textContent=o.active_jobs??'—';$('#cycleCount').textContent=(o.cycles||[]).length;$('#alertCount').textContent=(o.alerts||[]).length;
$('#portfolioMetrics').innerHTML=metric('Positions',p.position_count,'paper')+metric('Orders',p.orders,'paper')+metric('Fills',p.fills,'paper')+metric('Unrealized P&L',p.unrealized_pnl,'verified runtime');
$('#performanceMetrics').innerHTML=metric('Status',d.performance?.status||'—','paper analytics')+metric('Return',d.performance?.summary?.total_return_pct??'—','verified snapshot')+metric('Max drawdown',d.performance?.summary?.max_drawdown_pct??'—','paper history')+metric('Sharpe',d.performance?.summary?.sharpe??'—','when observations allow')+metric('Sortino',d.performance?.summary?.sortino??'—','when observations allow');
$('#learningMetrics').innerHTML=metric('Resolved',d.learning_diagnostics?.resolved??0,'observed outcomes')+metric('Hit rate',d.learning_diagnostics?.hit_rate??'—','verified')+metric('FP rate',d.learning_diagnostics?.false_positive_rate??'—','verified')+metric('Bias gap',d.learning_diagnostics?.overconfidence_gap??'—','absolute');
$('#readinessMetrics').innerHTML=metric('Overall',d.system_readiness?.overall??'—','engineering readiness')+metric('Data',d.system_readiness?.data_readiness??'—','provider boundary')+metric('Brain',d.system_readiness?.brain_readiness??'—','architecture')+metric('Portfolio',d.system_readiness?.portfolio_readiness??'—','paper/risk');
$('#opsMetrics').innerHTML=metric('Status',h.status,'control plane')+metric('Journal',d.journal?.integrity?'VERIFIED':'FAILED','hash chain')+metric('Cycles',(o.cycles||[]).length,'persistent')+metric('Live trading',d.live_trading_enabled?'ON':'OFF','safety boundary');
$('#positions').innerHTML=(p.positions||[]).length?`<div class="row head"><span>Security</span><span>Qty</span><span>Avg</span><span>Mark</span></div>`+(p.positions||[]).map(x=>`<div class="row"><span>${x.security_id}</span><span>${n(x.quantity)}</span><span>${n(x.avg_price)}</span><span>${n(x.mark_price)}</span></div>`).join(''):'No paper positions.';
$('#alerts').innerHTML=(o.alerts||[]).length?(o.alerts||[]).map(a=>`<div><span class="badge ${a.severity==='CRITICAL'?'red':'yellow'}">${a.severity}</span> ${a.code}: ${a.message}</div>`).join(''):'No active alerts.';
}
async function get(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
async function refresh(silent=false){try{render(await get('/api/state'));if(!silent)toast('Runtime refreshed')}catch(e){$('#connection').textContent='OFFLINE';$('#heroStatus').textContent='OFFLINE';$('#heroDetail').textContent='Runtime unavailable';if(!silent)toast('Runtime unavailable — no fake data shown')}}
async function loadHistory(){try{const rows=await get('/api/brain/history');$('#brainHistory').innerHTML=rows.length?`<div class="row head"><span>Cycle</span><span>Phase</span><span>Belief</span><span>Uncertainty</span></div>`+rows.slice(-20).reverse().map(x=>`<div class="row"><span>${x.cycle_id}</span><span>${x.phase}</span><span>${n(x.assessment?.belief)}</span><span>${n(x.assessment?.uncertainty)}</span></div>`).join(''):'No persisted cycles.'}catch(e){$('#brainHistory').textContent='History unavailable.'}}
async function loadCycles(){try{const d=await get('/api/state');const rows=d.operations?.cycles||[];$('#cycles').innerHTML=rows.length?`<div class="row head"><span>Cycle</span><span>Status</span><span>Started</span><span>Finished</span></div>`+rows.map(x=>`<div class="row"><span>${x.cycle_id}</span><span>${x.status}</span><span>${x.started_at}</span><span>${x.finished_at||'—'}</span></div>`).join(''):'No cycles recorded.'}catch(e){$('#cycles').textContent='Replay state unavailable.'}}
async function loadAudit(){try{const rows=await get('/api/audit?limit=30');$('#audit').innerHTML=rows.length?`<div class="row head"><span>Seq</span><span>Event</span><span>Hash</span><span>Payload</span></div>`+rows.slice().reverse().map(x=>`<div class="row"><span>${x.seq}</span><span>${x.event}</span><span>${String(x.hash).slice(0,14)}…</span><span>${JSON.stringify(x.payload).slice(0,70)}</span></div>`).join(''):'No audit events.'}catch(e){$('#audit').textContent='Audit unavailable.'}}
$('#refresh').onclick=()=>refresh();$('#opsRefresh').onclick=()=>refresh();$('#runtimeRefresh').onclick=()=>refresh();$('#loadHistory').onclick=loadHistory;$('#loadCycles').onclick=loadCycles;$('#loadAudit').onclick=loadAudit;
$('#search').addEventListener('keydown',e=>{if(e.key==='Enter'){const q=e.target.value.trim().toLowerCase();const hit=Object.entries(titles).find(([k,v])=>v.toLowerCase().includes(q)||k.includes(q));if(hit)showView(hit[0]);else toast('No runtime surface matched')}});
$('#copilotSend').onclick=async()=>{const q=$('#copilotInput').value.trim();if(!q)return;try{const r=await fetch('/api/copilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})});const d=await r.json();$('#copilotAnswer').textContent=d.answer||'No answer';}catch(e){$('#copilotAnswer').textContent='Runtime unavailable.'}};
refresh(true);setInterval(()=>refresh(true),30000);

async function loadProviders(){try{const rows=await get('/api/data/providers');const fresh=await get('/api/data/freshness');$('#providerSummary').textContent=rows.length?rows.map(x=>{const f=fresh.find(y=>y.provider===x.provider);return x.provider+': '+(f?f.status:(x.authenticated?'AUTHENTICATED':'NOT AUTHENTICATED'))}).join(' · '):'No providers registered';$('#providers').innerHTML=rows.length?'<div class="row head"><span>Provider</span><span>Configured</span><span>Authenticated</span><span>Reason</span></div>'+rows.map(x=>'<div class="row"><span>'+x.provider+'</span><span>'+x.configured+'</span><span>'+x.authenticated+'</span><span>'+x.reason+'</span></div>').join(''):'No provider configuration.'}catch(e){$('#providers').textContent='Provider status unavailable.'}}
async function loadLearning(){try{const d=await get('/api/learning');$('#learningMetrics').innerHTML=metric('Resolved',d.resolved??0,'observed outcomes')+metric('Hit rate',d.hit_rate??'—','verified')+metric('FP rate',d.false_positive_rate??'—','verified')+metric('Bias gap',d.overconfidence_gap??'—','absolute')}catch(e){}}
async function loadNav(){try{const d=await get('/api/paper/nav');$('#navHistory').innerHTML=d.history.length?'<div class="row head"><span>Timestamp</span><span>Cash</span><span>NAV</span><span>Positions</span></div>'+d.history.slice().reverse().map(x=>'<div class="row"><span>'+x.timestamp+'</span><span>'+n(x.cash)+'</span><span>'+n(x.nav)+'</span><span>'+n(x.payload?.positions?.length||0)+'</span></div>').join(''):'No NAV observations.'}catch(e){$('#navHistory').textContent='NAV history unavailable.'}}
async function loadPerformance(){try{const d=await get('/api/performance');const s=d.summary;$('#performanceDetail').innerHTML=s?'<div class="readiness"><div><b>Start NAV</b><span>'+n(s.start_nav)+'</span></div><div><b>End NAV</b><span>'+n(s.end_nav)+'</span></div><div><b>Observations</b><span>'+n(s.observations)+'</span></div><div><b>Lineage</b><span>'+String(s.lineage_hash).slice(0,18)+'…</span></div></div>':'No paper performance history yet.'}catch(e){$('#performanceDetail').textContent='Performance unavailable.'}}
async function loadValidation(){try{const d=await get('/api/validation');$('#validationDetail').innerHTML=`<div><b>Status</b><span>${d.status}</span></div><div><b>Forecast observations</b><span>${d.forecast_resolved??0}</span></div><div><b>Backtest observations</b><span>${d.backtest_observations??0}</span></div><div><b>Look-ahead rejected</b><span>${d.lookahead_rejections??0}</span></div><div><b>Lineage</b><span>${d.lineage_hash?String(d.lineage_hash).slice(0,18)+'…':'—'}</span></div><p class="muted">${d.note||''}</p>`}catch(e){$('#validationDetail').textContent='Validation unavailable.'}}
$('#loadProviders').onclick=loadProviders;$('#loadPerformance').onclick=loadPerformance;$('#loadLearning').onclick=loadLearning;$('#loadNav').onclick=loadNav;$('#loadValidation').onclick=loadValidation;
loadValidation();

async function loadRisk(){try{const d=await get('/api/risk/overview');$('#riskResult').innerHTML=(d.layers||[]).map(x=>`<article class="panel"><b>${x.replaceAll('_',' ')}</b><p class="muted">${d.note}</p><span class="badge ${d.status==='READY'?'green':'yellow'}">${d.status}</span></article>`).join('')}catch(e){$('#riskResult').textContent='Risk surface unavailable.'}}
$('#companyCheck').onclick=async()=>{const sid=$('#companyId').value.trim();if(!sid)return toast('Enter a security ID');try{const d=await get('/api/explorer/company?security_id='+encodeURIComponent(sid));$('#companyResult').innerHTML=`<div><b>${d.security_id}</b><span>${d.status}</span></div><div><b>Coverage</b><span>${n(d.coverage_pct)}%</span></div><div><b>Blockers</b><span>${(d.blockers||[]).join(', ')||'None'}</span></div><div><b>Next actions</b><span>${(d.next_actions||[]).join(', ')}</span></div>`}catch(e){$('#companyResult').textContent='Company readiness unavailable.'}};
$('#sectorCheck').onclick=async()=>{const sid=$('#sectorId').value.trim();if(!sid)return toast('Enter a sector');try{const d=await get('/api/explorer/sector?sector='+encodeURIComponent(sid));$('#sectorResult').innerHTML=`<div><b>${d.sector}</b><span>${d.status}</span></div><div><b>Layers</b><span>${(d.supported_layers||[]).join(' · ')}</span></div><div><b>Boundary</b><span>${d.message}</span></div>`}catch(e){$('#sectorResult').textContent='Sector layer unavailable.'}};
